// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/MukizuL/GophKeeper/internal/proto (interfaces: Gophkeeper_CreateDataServer,Gophkeeper_DownloadServer)
//
// Generated by this command:
//
//	mockgen . Gophkeeper_CreateDataServer,Gophkeeper_DownloadServer
//

// Package mock_proto is a generated GoMock package.
package mockpb

import (
	context "context"
	reflect "reflect"

	proto "github.com/MukizuL/GophKeeper/internal/proto"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockGophkeeper_CreateDataServer is a mock of Gophkeeper_CreateDataServer interface.
type MockGophkeeper_CreateDataServer[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]
	isgomock struct{}
}

// MockGophkeeper_CreateDataServerMockRecorder is the mock recorder for MockGophkeeper_CreateDataServer.
type MockGophkeeper_CreateDataServerMockRecorder[Req any, Res any] struct {
	mock *MockGophkeeper_CreateDataServer[Req, Res]
}

// NewMockGophkeeper_CreateDataServer creates a new mock instance.
func NewMockGophkeeper_CreateDataServer[Req any, Res any](ctrl *gomock.Controller) *MockGophkeeper_CreateDataServer[Req, Res] {
	mock := &MockGophkeeper_CreateDataServer[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockGophkeeper_CreateDataServerMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) EXPECT() *MockGophkeeper_CreateDataServerMockRecorder[Req, Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).Context))
}

// Recv mocks base method.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) Recv() (*proto.CreateDataRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.CreateDataRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockGophkeeper_CreateDataServer[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).RecvMsg), m)
}

// SendAndClose mocks base method.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) SendAndClose(arg0 *proto.CreateDataResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) SendAndClose(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).SendAndClose), arg0)
}

// SendHeader mocks base method.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockGophkeeper_CreateDataServer[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockGophkeeper_CreateDataServer[Req, Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockGophkeeper_CreateDataServerMockRecorder[Req, Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockGophkeeper_CreateDataServer[Req, Res])(nil).SetTrailer), arg0)
}

// MockGophkeeper_DownloadServer is a mock of Gophkeeper_DownloadServer interface.
type MockGophkeeper_DownloadServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockGophkeeper_DownloadServerMockRecorder[Res]
	isgomock struct{}
}

// MockGophkeeper_DownloadServerMockRecorder is the mock recorder for MockGophkeeper_DownloadServer.
type MockGophkeeper_DownloadServerMockRecorder[Res any] struct {
	mock *MockGophkeeper_DownloadServer[Res]
}

// NewMockGophkeeper_DownloadServer creates a new mock instance.
func NewMockGophkeeper_DownloadServer[Res any](ctrl *gomock.Controller) *MockGophkeeper_DownloadServer[Res] {
	mock := &MockGophkeeper_DownloadServer[Res]{ctrl: ctrl}
	mock.recorder = &MockGophkeeper_DownloadServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophkeeper_DownloadServer[Res]) EXPECT() *MockGophkeeper_DownloadServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockGophkeeper_DownloadServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockGophkeeper_DownloadServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockGophkeeper_DownloadServer[Res]) Send(arg0 *proto.DownloadResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockGophkeeper_DownloadServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockGophkeeper_DownloadServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockGophkeeper_DownloadServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockGophkeeper_DownloadServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockGophkeeper_DownloadServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockGophkeeper_DownloadServer[Res])(nil).SetTrailer), arg0)
}
