// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=mocks/services.go -package=mockservices
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	proto "github.com/MukizuL/GophKeeper/internal/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockServicesI is a mock of ServicesI interface.
type MockServicesI struct {
	ctrl     *gomock.Controller
	recorder *MockServicesIMockRecorder
	isgomock struct{}
}

// MockServicesIMockRecorder is the mock recorder for MockServicesI.
type MockServicesIMockRecorder struct {
	mock *MockServicesI
}

// NewMockServicesI creates a new mock instance.
func NewMockServicesI(ctrl *gomock.Controller) *MockServicesI {
	mock := &MockServicesI{ctrl: ctrl}
	mock.recorder = &MockServicesIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicesI) EXPECT() *MockServicesIMockRecorder {
	return m.recorder
}

// CreateBank mocks base method.
func (m *MockServicesI) CreateBank(ctx context.Context, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBank", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBank indicates an expected call of CreateBank.
func (mr *MockServicesIMockRecorder) CreateBank(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBank", reflect.TypeOf((*MockServicesI)(nil).CreateBank), ctx, data)
}

// CreateData mocks base method.
func (m *MockServicesI) CreateData(ctx context.Context, token string, stream proto.Gophkeeper_CreateDataServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", ctx, token, stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateData indicates an expected call of CreateData.
func (mr *MockServicesIMockRecorder) CreateData(ctx, token, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockServicesI)(nil).CreateData), ctx, token, stream)
}

// CreateNewUser mocks base method.
func (m *MockServicesI) CreateNewUser(ctx context.Context, login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewUser", ctx, login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewUser indicates an expected call of CreateNewUser.
func (mr *MockServicesIMockRecorder) CreateNewUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewUser", reflect.TypeOf((*MockServicesI)(nil).CreateNewUser), ctx, login, password)
}

// CreatePassword mocks base method.
func (m *MockServicesI) CreatePassword(ctx context.Context, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePassword", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePassword indicates an expected call of CreatePassword.
func (mr *MockServicesIMockRecorder) CreatePassword(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePassword", reflect.TypeOf((*MockServicesI)(nil).CreatePassword), ctx, data)
}

// CreateTextual mocks base method.
func (m *MockServicesI) CreateTextual(ctx context.Context, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTextual", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTextual indicates an expected call of CreateTextual.
func (mr *MockServicesIMockRecorder) CreateTextual(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTextual", reflect.TypeOf((*MockServicesI)(nil).CreateTextual), ctx, data)
}

// Download mocks base method.
func (m *MockServicesI) Download(ctx context.Context, token, id string, stream proto.Gophkeeper_DownloadServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, token, id, stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockServicesIMockRecorder) Download(ctx, token, id, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockServicesI)(nil).Download), ctx, token, id, stream)
}

// GetBank mocks base method.
func (m *MockServicesI) GetBank(ctx context.Context) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBank", ctx)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBank indicates an expected call of GetBank.
func (mr *MockServicesIMockRecorder) GetBank(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBank", reflect.TypeOf((*MockServicesI)(nil).GetBank), ctx)
}

// GetData mocks base method.
func (m *MockServicesI) GetData(ctx context.Context) ([]*proto.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", ctx)
	ret0, _ := ret[0].([]*proto.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockServicesIMockRecorder) GetData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockServicesI)(nil).GetData), ctx)
}

// GetPasswords mocks base method.
func (m *MockServicesI) GetPasswords(ctx context.Context) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswords", ctx)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswords indicates an expected call of GetPasswords.
func (mr *MockServicesIMockRecorder) GetPasswords(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswords", reflect.TypeOf((*MockServicesI)(nil).GetPasswords), ctx)
}

// GetText mocks base method.
func (m *MockServicesI) GetText(ctx context.Context) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetText", ctx)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetText indicates an expected call of GetText.
func (mr *MockServicesIMockRecorder) GetText(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetText", reflect.TypeOf((*MockServicesI)(nil).GetText), ctx)
}

// Login mocks base method.
func (m *MockServicesI) Login(ctx context.Context, login, password string) (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockServicesIMockRecorder) Login(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockServicesI)(nil).Login), ctx, login, password)
}
