// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mocks/storage.go -package=mockstorage
//

// Package mockstorage is a generated GoMock package.
package mockstorage

import (
	context "context"
	reflect "reflect"

	dto "github.com/MukizuL/GophKeeper/internal/dto"
	models "github.com/MukizuL/GophKeeper/internal/models"
	proto "github.com/MukizuL/GophKeeper/internal/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateBank mocks base method.
func (m *MockRepository) CreateBank(ctx context.Context, userID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBank", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBank indicates an expected call of CreateBank.
func (mr *MockRepositoryMockRecorder) CreateBank(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBank", reflect.TypeOf((*MockRepository)(nil).CreateBank), ctx, userID, data)
}

// CreateData mocks base method.
func (m *MockRepository) CreateData(ctx context.Context, id string, stream proto.Gophkeeper_CreateDataServer) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", ctx, id, stream)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateData indicates an expected call of CreateData.
func (mr *MockRepositoryMockRecorder) CreateData(ctx, id, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockRepository)(nil).CreateData), ctx, id, stream)
}

// CreateNewUser mocks base method.
func (m *MockRepository) CreateNewUser(ctx context.Context, login string, passwordHash, salt []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewUser", ctx, login, passwordHash, salt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewUser indicates an expected call of CreateNewUser.
func (mr *MockRepositoryMockRecorder) CreateNewUser(ctx, login, passwordHash, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewUser", reflect.TypeOf((*MockRepository)(nil).CreateNewUser), ctx, login, passwordHash, salt)
}

// CreatePassword mocks base method.
func (m *MockRepository) CreatePassword(ctx context.Context, userID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePassword", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePassword indicates an expected call of CreatePassword.
func (mr *MockRepositoryMockRecorder) CreatePassword(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePassword", reflect.TypeOf((*MockRepository)(nil).CreatePassword), ctx, userID, data)
}

// CreateReference mocks base method.
func (m *MockRepository) CreateReference(ctx context.Context, userID, id string, filename []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReference", ctx, userID, id, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReference indicates an expected call of CreateReference.
func (mr *MockRepositoryMockRecorder) CreateReference(ctx, userID, id, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReference", reflect.TypeOf((*MockRepository)(nil).CreateReference), ctx, userID, id, filename)
}

// CreateTextual mocks base method.
func (m *MockRepository) CreateTextual(ctx context.Context, userID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTextual", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTextual indicates an expected call of CreateTextual.
func (mr *MockRepositoryMockRecorder) CreateTextual(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTextual", reflect.TypeOf((*MockRepository)(nil).CreateTextual), ctx, userID, data)
}

// Download mocks base method.
func (m *MockRepository) Download(ctx context.Context, id string, stream proto.Gophkeeper_DownloadServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, id, stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockRepositoryMockRecorder) Download(ctx, id, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockRepository)(nil).Download), ctx, id, stream)
}

// GetBankByUserID mocks base method.
func (m *MockRepository) GetBankByUserID(ctx context.Context, id string) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankByUserID", ctx, id)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankByUserID indicates an expected call of GetBankByUserID.
func (mr *MockRepositoryMockRecorder) GetBankByUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankByUserID", reflect.TypeOf((*MockRepository)(nil).GetBankByUserID), ctx, id)
}

// GetPasswordsByUserID mocks base method.
func (m *MockRepository) GetPasswordsByUserID(ctx context.Context, id string) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordsByUserID", ctx, id)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordsByUserID indicates an expected call of GetPasswordsByUserID.
func (mr *MockRepositoryMockRecorder) GetPasswordsByUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordsByUserID", reflect.TypeOf((*MockRepository)(nil).GetPasswordsByUserID), ctx, id)
}

// GetReferenceByUserID mocks base method.
func (m *MockRepository) GetReferenceByUserID(ctx context.Context, userID string) ([]dto.FileReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferenceByUserID", ctx, userID)
	ret0, _ := ret[0].([]dto.FileReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferenceByUserID indicates an expected call of GetReferenceByUserID.
func (mr *MockRepositoryMockRecorder) GetReferenceByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferenceByUserID", reflect.TypeOf((*MockRepository)(nil).GetReferenceByUserID), ctx, userID)
}

// GetTextualByUserID mocks base method.
func (m *MockRepository) GetTextualByUserID(ctx context.Context, id string) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextualByUserID", ctx, id)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextualByUserID indicates an expected call of GetTextualByUserID.
func (mr *MockRepositoryMockRecorder) GetTextualByUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextualByUserID", reflect.TypeOf((*MockRepository)(nil).GetTextualByUserID), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(ctx context.Context, id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), ctx, id)
}

// GetUserByLogin mocks base method.
func (m *MockRepository) GetUserByLogin(ctx context.Context, login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockRepository)(nil).GetUserByLogin), ctx, login)
}
